# Render Blueprint for Bhisey Backend Deployment
# This file configures automatic deployment when connected to GitHub

services:
  # Backend API Service
  - type: web
    name: bhisey-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: bhisey-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
        sync: false
      - key: JWT_REFRESH_SECRET
        generateValue: true
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  # PostgreSQL Database
  - name: bhisey-db
    databaseName: bhisey
    user: bhisey_admin
    plan: free

# Note: This configuration file is optional but recommended
# It allows one-click deployment from Render dashboard